name: Java CI with Gradle

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Create Configuration Files
      run: |
        mkdir -p ./src/main/resources
        echo "${{ secrets.APPLICATION_YAML }}" > ./src/main/resources/application.yaml
        mkdir -p ./src/test/resources
        echo "${{ secrets.APPLICATION_TEST_YAML }}" > ./src/test/resources/application-test.yaml

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build -Dspring.profiles.active=test --info

    - name: Deliver JAR to GCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_SSH_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        source: "build/libs/*-SNAPSHOT.jar"
        target: "~/inform-main"
        strip_components: 2

    - name: Deliver Deploy Files to GCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_SSH_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        source: "Dockerfile,nginx,init-letsencrypt.sh"
        target: "deploy_temp"

    - name: Deploy to GCP
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_SSH_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          # 1. 파일 옮기기 (temp -> real)
          mkdir -p ~/inform-main
          # 숨김 파일(.env 등)까지 싹 다 옮기기 위해 . 포함
          cp -r ~/deploy_temp/* ~/inform-main/
          rm -rf ~/deploy_temp
          
          cd ~/inform-main
          # 2. 캐시 없이 새로운 이미지 강제 빌드
          docker build --no-cache -t inform-main-backend .
          
          # 3. 기존 앱 컨테이너 중지 및 제거
          docker stop my-api-server || true
          docker rm my-api-server || true
          
          # 4. docker compose로 전체 서비스 재시작 (네트워크 자동 구성)
          docker compose up -d --force-recreate

